# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20190529_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
