# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_remove_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pub_date_created',
        ),
    ]
